### PR TITLE
better error reporting for timeouts; fix internal timeout api usage

### PR DESCRIPTION
**Pull request by EndangeredMassa**
I'm getting a timeout running the tests locally. I noticed that the timeout registration was broken. So, I fixed that, but I'm still not sure why I'm seeing a timeout here.

```
$ npm test

> webdriver-http-sync@1.0.0 pretest /home/sean/source/webdriver-http-sync
> npm run build


> webdriver-http-sync@1.0.0 build /home/sean/source/webdriver-http-sync
> npub prep && coffee -cbo lib src


> webdriver-http-sync@1.0.0 test /home/sean/source/webdriver-http-sync
> mocha


  Webdriver
PhantomJS is launching GhostDriver...
[INFO  - 2015-03-18T15:11:31.640Z] GhostDriver - Main - running on port 4499
    1) "before all" hook: create driver

  request
[INFO  - 2015-03-18T15:11:31.652Z] Session [0f249b10-cd81-11e4-a732-8f5dc8231bc4] - CONSTRUCTOR - Desired Capabilities: {"browserName":"phantomjs"}
[INFO  - 2015-03-18T15:11:31.652Z] Session [0f249b10-cd81-11e4-a732-8f5dc8231bc4] - CONSTRUCTOR - Negotiated Capabilities: {"browserName":"phantomjs","version":"1.9.0","driverName":"ghostdriver","driverVersion":"1.0.3","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2015-03-18T15:11:31.652Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 0f249b10-cd81-11e4-a732-8f5dc8231bc4
    ✓ sends a GET request 
    ✓ sends a POST request 


  2 passing (4s)
  1 failing

  1) Webdriver "before all" hook: create driver:
     Error: Assertion failed: Failed to start WebDriver session: Error: Request connection timed out after 2000ms to: http://127.0.0.1:4499/session
  at Object.callback (/home/sean/source/webdriver-http-sync/lib/request.js:101:22)
  at Object.CurlRequest.end (/home/sean/source/webdriver-http-sync/node_modules/http-sync/http-sync.js:86:34)
  at /home/sean/source/webdriver-http-sync/lib/request.js:103:18
  at module.exports (/home/sean/source/webdriver-http-sync/lib/session.js:48:14)
  at new WebDriver (/home/sean/source/webdriver-http-sync/lib/index.js:75:11)
  at Context.<anonymous> (/home/sean/source/webdriver-http-sync/test/driver.test.coffee:43:19)
  at callFn (/home/sean/source/webdriver-http-sync/node_modules/mocha/lib/runnable.js:266:21)
  at Hook.Runnable.run (/home/sean/source/webdriver-http-sync/node_modules/mocha/lib/runnable.js:259:7)
  at next (/home/sean/source/webdriver-http-sync/node_modules/mocha/lib/runner.js:268:10)
  at /home/sean/source/webdriver-http-sync/node_modules/mocha/lib/runner.js:284:7
  at done (/home/sean/source/webdriver-http-sync/node_modules/mocha/lib/runnable.js:222:5)
  at /home/sean/source/webdriver-http-sync/node_modules/mocha/lib/runnable.js:242:9
  at Socket.<anonymous> (/home/sean/source/webdriver-http-sync/test/driver.test.coffee:38:9)
  at Socket.emit (events.js:117:20)
  at Socket.<anonymous> (_stream_readable.js:765:14)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at emitReadable (_stream_readable.js:423:5)
  at readableAddChunk (_stream_readable.js:166:9)
  at Socket.Readable.push (_stream_readable.js:128:10)
  at Pipe.onread (net.js:529:21)

Expected: 408
Actually: 200
    at error (/home/sean/source/webdriver-http-sync/node_modules/assertive/lib/assertive.js:441:12)
    at Object.assert.equal (/home/sean/source/webdriver-http-sync/node_modules/assertive/lib/assertive.js:105:15)
    at module.exports (/home/sean/source/webdriver-http-sync/lib/session.js:49:10)
    at new WebDriver (/home/sean/source/webdriver-http-sync/lib/index.js:75:11)
    at Context.<anonymous> (/home/sean/source/webdriver-http-sync/test/driver.test.coffee:43:19)
    at callFn (/home/sean/source/webdriver-http-sync/node_modules/mocha/lib/runnable.js:266:21)
    at Hook.Runnable.run (/home/sean/source/webdriver-http-sync/node_modules/mocha/lib/runnable.js:259:7)
    at next (/home/sean/source/webdriver-http-sync/node_modules/mocha/lib/runner.js:268:10)
    at /home/sean/source/webdriver-http-sync/node_modules/mocha/lib/runner.js:284:7
    at done (/home/sean/source/webdriver-http-sync/node_modules/mocha/lib/runnable.js:222:5)
    at /home/sean/source/webdriver-http-sync/node_modules/mocha/lib/runnable.js:242:9
    at Socket.<anonymous> (/home/sean/source/webdriver-http-sync/test/driver.test.coffee:38:9)
    at Socket.emit (events.js:117:20)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at Pipe.onread (net.js:529:21)
  

npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

### CODE REVIEW

**Comment by EndangeredMassa** [comment]
This was a phantomjs version issue. After updating to 1.9.8, the tests pass for me locally.

**Comment by EndangeredMassa** [comment]
@jkrems fixes timeout usage from https://github.com/groupon-testium/webdriver-http-sync/pull/26

**Comment by jkrems** [comment]
LGTM! I think the previous behavior was to throw an error instead of creating a fake response. I don't feel strongly either way. What was your reason for the faux response?

**Comment by EndangeredMassa** [comment]
Ah, yes. That was the previous behavior.

This behavior makes the error more obvious while still including a lot of detail. I also don't feel strongly about it, though.

**Comment by jkrems** [comment]
The problem I see here is that it's possible to ignore errors (or rather: miss errors). E.g. if something just calls the `POST /session/xy/input` and does not explicitly check the status code, it will silently fail. Maybe a `gofer`-style error with `httpHeaders`/`body` properties would make sense? Same information available but it can't be missed by accident?

**Comment by EndangeredMassa** [comment]
Ah, I was using it to throw an error in a different location (in src/session), but yes, this will also possibly hide an error from the library user, which is bad.

**Comment by EndangeredMassa** [comment]
Switching timeouts to throw errors instead. Added a test for it.

**Comment by jkrems** [comment]
:shipit:

**Comment by EndangeredMassa** [comment]
[1.1.0](https://github.com/groupon-testium/webdriver-http-sync/releases/tag/v1.1.0)

**Pull request merged**
